version: '3'

services:
  db:
    container_name: pg_container
    image: "postgres:${POSTGRES_VERSION}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - ./postgre-data:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network
networks: 
  postgres-compose-network:
    driver: bridge